# Generated by Django 4.1.2 on 2023-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_link_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.TextField(default='https://youtube.com', max_length=300),
        ),
    ]
