# Generated by Django 4.1.2 on 2023-01-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_demolink_project_downlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentor', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcomments', verbose_name='Reply to')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Blog')),
            ],
        ),
    ]
