# Generated by Django 4.1.2 on 2023-01-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_tags_projectcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomments',
            name='parent',
        ),
        migrations.AlterField(
            model_name='projectcomments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
