# Generated by Django 4.1.2 on 2023-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang',
            field=models.TextField(blank=True),
        ),
    ]
