# Generated by Django 4.1.2 on 2023-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='shehbaz', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='sno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
