# Generated by Django 4.1.2 on 2023-01-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomments', verbose_name='Reply to'),
        ),
    ]
