# Generated by Django 4.1.2 on 2023-01-03 06:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(max_length=150),
        ),
    ]
