# Generated by Django 4.1.2 on 2023-01-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_about_alter_social_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='content',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
