# Generated by Django 4.1.2 on 2023-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_testimonials_content_testimonials_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
