# Generated by Django 4.1.2 on 2023-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_about_about_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
