# Generated by Django 4.1.2 on 2023-01-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='link',
            field=models.CharField(default='https://fiverr.com/shehbaz_alam_b', max_length=250),
        ),
    ]
